server:
  port: 8132

community:
  test-controls:
    enabled: false

activity:
  test-controls:
    enabled: false

calendar:
  test-controls:
    enabled: false

changelog:
  test-controls:
    enabled: false
