server:
  port: 8125

spring:
  mvc:
    dispatch-trace-request: true

api-gateway:
  internal-signing-secret: local-test-gateway-signing-secret
  upstreams:
    portal-core-base-url: http://127.0.0.1:8134
    ops-core-base-url: http://127.0.0.1:8133
